### PR TITLE
Add maxBuffer option + typescript declarations

### PR DESCRIPTION
**Pull request by Arseny271**
To get large json, for example with a large bag of files, I need to increase the `maxBuffer` parameter.

### CODE REVIEW

**Comment by Telman1991** [comment]
Xbxbxnzjnxnxx

**Comment by Telman1991** [comment]
Sbsbdbx

**Comment by ndatg** [comment]
I'll update it soon

**Comment by ndatg** [comment]
resolved in b84523d0ede657b794bf7f23210db2b819aead29

**Pull request closed without merging**
